# Generated by Django 5.1.5 on 2025-01-31 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_userprofile'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='option',
            unique_together=set(),
        ),
    ]
