# Generated by Django 5.1.5 on 2025-02-07 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_remove_userprofile_avatar_userprofile_course_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='reg_number',
            new_name='registration_number',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
